spring:
  application:
    name: workshop-be-sql

  datasource:
    url: jdbc:postgresql://turntable.proxy.rlwy.net:47505/railway
    username: postgres
    password: xQPukItHeDhbmKPgdztbmVHzXqwvqWMH
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
