spring:
  application:
    name: workshop-be-sql
    
  datasource:
    url: jdbc:mysql://localhost:3306/sba-workshop?useSSL=true&requireSSL=true&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

app:
  jwt:
    secret: 1daa7bd734896c27185b8468133c820c
    expiration-ms: 1440000

  springdoc:
    api-docs.path: /v3/api-docs
    swagger-ui.path: /swagger-ui.html
